; <?php return; ?> DO NOT DELETE THIS LINE
dbtype="mysql"
dbhost="localhost"
dbport="3306"
dbuser="__DB_USER__"
dbpass="__DB_PWD__"
dbname="__DB_NAME__"
tblpfx="wt_"
base_url="https://__DOMAIN____PATH__"
rewrite_urls="0"
