#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit on command errors and treat access to unset variables as an error
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Get the _common.sh file if it's not in the current directory
	cp ../settings/scripts/_common.sh ./_common.sh
	chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

# See comsudo yunohost app ssowatconfments in install script
app=$YNH_APP_INSTANCE_NAME


# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)
path_url=$(ynh_app_setting_get "$app" path)
final_path=$(ynh_app_setting_get $app final_path)
db_name=$(ynh_app_setting_get $app db_name)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================

yunohost app checkurl "${domain}${path_url}" -a "$app" \
	|| ynh_die "Path not available: ${domain}${path_url}"
test ! -d $final_path \
	|| ynh_die "There is already a directory: $final_path "

  #=================================================
  # STANDARD RESTORATION STEPS
  #=================================================
  # RESTORE THE NGINX CONFIGURATION
  #=================================================

  ynh_restore_file "/etc/nginx/conf.d/$domain.d/$app.conf"

  #=================================================
  # RESTORE THE APP MAIN DIR
  #=================================================

  ynh_restore_file "$final_path"

# Restore permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
sudo chown -R root: "${final_path}"


#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================

db_pwd=$(ynh_app_setting_get $app mysqlpwd)
ynh_mysql_setup_db $db_name $db_name $db_pwd
ynh_mysql_connect_as $db_name $db_pwd $db_name < ./db.sql
### PHP (remove if not used) ###
# If a dedicated php-fpm process is used:
# # Copy PHP-FPM pool configuration and reload the service
# sudo cp -a ./php-fpm.conf "/etc/php5/fpm/pool.d/${app}.conf"
# sudo service php5-fpm reload
### PHP end ###


sudo chmod -R 777 $final_path/data

# Restart webserver
systemctl reload php5-fpm
sudo service nginx reload
